remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 
title: Antonio Cozzolino/projects
description: Welcome to my GitHub repository for showcasing my projects! This page contains links and descriptions to source code for my personal portfolio. Here, you'll find a curated collection of my work, including detailed descriptions and code of various projects I've developed. 
